apiVersion: batch/v1
kind: Job
metadata:
  name: dev-idsvr-1-cluster-conf-job
  labels:
    app.kubernetes.io/name: idsvr
    helm.sh/chart: idsvr-0.9.19
    app.kubernetes.io/instance: dev
    app.kubernetes.io/managed-by: Helm
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: dev-idsvr-cluster-conf-job
          image: "custom_idsvr:6.1.0"
          command: ["sh",  "/opt/idsvr/bin/createConfigSecret.sh"]
          env:
            - name: CONFIG_SERVICE_HOST
              value: dev-idsvr-admin-svc
            - name: CONFIG_SERVICE_PORT
              value: "6789"
            - name: SECRET_NAME
              value: dev-idsvr-cluster-config-xml
            - name: REVISION
              value: "1"
            
          volumeMounts:
            - name: entrypoint-volume
              mountPath: /opt/idsvr/bin/createConfigSecret.sh
              subPath: createConfigSecret.sh
      volumes:
        - name: entrypoint-volume
          configMap:
            name: dev-idsvr-cluster-conf-map
      serviceAccountName: dev-idsvr-service-account
      restartPolicy: Never