apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-idsvr-service-account
  labels:
    app.kubernetes.io/name: idsvr
    helm.sh/chart: idsvr-0.9.19
    app.kubernetes.io/instance: dev
    app.kubernetes.io/managed-by: Helm