#
# A minimal custom values file for the Curity Identity Server
#

replicaCount: 2

image:
  repository: custom_idsvr
  tag: 8.0.0
  pullPolicy: Never

curity:
  #runtime:
  #  podLabels:
  #    sidecar.istio.io/inject: true

  config:
    uiEnabled: true
    backup: false
    skipInstall: false
    password: Password1
    configuration:
      - configMapRef:
         name: idsvr-configbackup
         items:
           - key: configbackup
             path: idsvr-config-backup.xml

# The Curity Identity Server is exposed over HTTPS port 443 using Istio custom resource definitions
ingress:
  enabled: false
