#
# A minimal custom values file for the Curity Identity Server, for an Istio deployment
#

replicaCount: 2

image:
  repository: custom_idsvr
  tag: latest

curity:
  adminUiHttp: true
  admin:
    podLabels:
      sidecar.istio.io/inject: 'true'
    logging:
      level: INFO

  runtime:
    podLabels:
      sidecar.istio.io/inject: 'true'
    serviceAccount:
      name: curity-idsvr-service-account
    logging:
      level: INFO

  config:
    uiEnabled: true
    skipInstall: true
    backup: false
    encryptionKey: $CONFIG_ENCRYPTION_KEY
    environmentVariableSecrets:
      - idsvr-secure-properties

# Custom resource definitions for Istio's gateway expose the Curity Identity Server over port 443
ingress:
  enabled: false
