#
# A minimal custom values file for the Curity Identity Server
#

replicaCount: 2

image:
  repository: custom_idsvr
  tag: 8.0.0

curity:
  admin:
    podLabels:
      sidecar.istio.io/inject: 'true'

  runtime:
    podLabels:
      sidecar.istio.io/inject: 'true'

  config:
    uiEnabled: true
    skipInstall: true
    backup: false
    encryptionKey: bdb95b38279b6018b2002adb438010167b6b730e3ab198c77e65df7501ca08fc
    configuration:
      - configMapRef:
         name: idsvr-configbackup
         items:
           - key: configbackup
             path: idsvr-config-backup.xml

# This example uses Istio's gateway to expose the Curity Identity Server over port 443
ingress:
  enabled: false
