#
# Expose the identity server's HTTP endpoints using the below DNS names
# The TLS part of the connection is specified separately in the Destination Rules
#

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: idsvr-admin-virtualservice
spec:
  hosts:
  - admin.example.com  
  gateways:
  - idsvr-admin-gateway
  http:
  - route:
    - destination:
        host: curity-idsvr-admin-svc
        port:
          number: 6749
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: idsvr-runtime-virtualservice
spec:
  hosts:
  - login.example.com
  gateways:
  - idsvr-runtime-gateway
  http:
  - route:
    - destination:
        host: curity-idsvr-runtime-svc
        port:
          number: 8443