#
# The Curity namespace uses sidecars and mTLS in a partial way
# The applications namespace uses sidecars and mTLS for all pods
#
kind: Namespace
apiVersion: v1
metadata:
  name: curity
---
kind: Namespace
apiVersion: v1
metadata:
  name: applications
  labels:
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: applications
spec:
  mtls:
    mode: STRICT
