#
# A basic Kubernetes deployment file for MySql that avoids persistent storage for simplicity
#

kind: Service
apiVersion: v1
metadata:
  name: mysql-svc
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - protocol: "TCP"
      port: 3306
      nodePort: 30306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.22
          volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: init-script
            readOnly: true
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Password1
            - name: MYSQL_DATABASE
              value: idsvr
          ports:
            - containerPort: 3306
              name: mysql
      volumes:
        - name: init-script
          configMap:
            name: init-script-configmap
